
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/study?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.222.129
    port: 21080
server:
  port: 6001
  context-path: /sell

mybatis:
  mapper-locations: classpath:mapper/*.xml
